#!/bin/bash

domain=$1
date=`date +%Y%m%d`
localzone="/etc/bind/named.conf.local"
root="/etc/bind/zones/db.thijs-vercammen.sb.uclllabs.be"
zone="/etc/bind/zones/db.$domain.thijs-vercammen.sb.uclllabs.be"


echo -e "\$TTL 3600
$domain.thijs-vercammen.sb.uclllabs.be.	IN  SOA  ns.$domain.thijs-vercammen.sb.uclllabs.be. admin.$domain.thijs-vercammen.sb.uclllabs.be.(
\t$date"1"; Serial
\t3600; Refresh
\t900; Retry
\t3600; Expire
\t3600); Negative Cache TTL

$domain.thijs-vercammen.sb.uclllabs.be. \tIN\tNS\t ns.thijs-vercammen.sb.uclllabs.be.
$domain.thijs-vercammen.sb.uclllabs.be. \tIN\tNS\t ns.uclllabs.be." > $zone

echo -e "zone $domain.thijs-vercammen.sb.uclllabs.be{
\ttype master;
\tfile \"/etc/bind/zones/db."$domain".thijs-vercammen.sb.uclllabs.be\";
};" >> $localzone

echo -e ""$domain".thijs-vercammen.sb.uclllabs.be.\tIN\tNS\t ns.thijs-vercammen.sb.uclllabs.be." >> $root
service bind9 restart

echo "Done!"
