#!/bin/bash

$recordType
$typeValue
$domain
$ip
$zone
recordType=$2;
typeValue=$3;
domain=$5;
ip=$4;


#if [$recordType = "MX"]; then
#        echo -e "@     IN      MX       10 $typeValue" >> /etc/bind/zones/db.$domain;
#        echo -e "$typeValue     IN      A       $ip" >> /etc/bind/zones/db.$domain;
#fi
	echo -e "$typeValue.$domain	IN	$recordType	$ip" >> /etc/bind/zones/db.$domain;

line=$(grep "Serial" /etc/bind/zones/db.$domain)
number=$(echo $line | cut -d \; -f 1)
((number++))
line2="$number; Serial"
echo $line2;
sed -i "s/.*Serial.*/\t$line2/g" /etc/bind/zones/db.$domain


systemctl restart bind9
